name: CI for Go Code #Naming the workflow
on: # for event triggering
  push:
    branches: [main] # add with comma for more branches to monitor
  pull_request:
    branches: [main]
    
jobs: # job to execute
  build: # name of the job, build is a customised name eg. job1, job2
    name: Load OS # name for printing
    runs-on: ubuntu-latest # specify os in virtual machine
    steps:
    - name: Print hello
      run: | # run terminal command
        ls
        echo Hello!
        
    - name: Setup Go
      uses: actions/setup-go@v3.2.0
      with:
        go-version: 1.18
    - name: Check Go Version
      run: go version
    
    - name: Checkout Repo
      uses: actions/checkout@v2.4.2
    
    - name: Checkout Remote Private Repo
      uses: actions/checkout@v2.4.2
      with:
        repository: lowkh2/GoSchoolRemoteExample
        token: ${{ secrets.GO_SECRET }}
        path: remote
    - name: Check remote files
      run: |
        cd remote
        ls
        cat myText.txt
        cd ..
      
    - name: Check File System
      run: ls
      
    - name: Install dependencies
      run: |
        go mod init calc # Add go mod and go sum file. So when we use go build, we can omit line 33 - 35
        go mod tidy
        go get github.com/franela/goblin
        go install github.com/tebeka/go2xunit # https://github.com/tebeka/go2xunit
        go test -v
        go test -v | go2xunit -output tests.xml # generate xml file
        
    - name: Publish Test Results # https://github.com/EnricoMi/publish-unit-test-result-action
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always() # continue regardless the previous build is successful or has failed
      with:
        files: tests.xml
        
    - if: ${{ failure() }} # if something went wrong
      uses: nashmaniac/create-issue-action@v1.1 # https://github.com/nashmaniac/create-issue-action
      name: Create Issue Action
      with:
        title: Build Failed
        token: ${{secrets.GITHUB_TOKEN}} # your own github token to access to repo itself
        assignees: ${{github.actor}}
        labels: worflow-failed
        body: Workflow failed for commit ${{github.sha}} # commit id
